name: Publish Docker image

on:
  push:
    tags:
      - 'v*'

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    env:
      ANTORA_VERSION: 2.3.4
      IMAGE_REPO: ggrossetie/antora-lunr
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Docker meta
        id: metadata
        uses: crazy-max/ghaction-docker-meta@v2.3.0
        with:
          # list of Docker images to use as base name for tags
          images: |
            ${{ env.IMAGE_REPO }}
          flavor: |
            latest=auto
          tags: |
            type=semver,enable=true,priority=900,prefix=${{ env.ANTORA_VERSION }}-lunr,pattern={{version}}
            type=raw,enable=true,priority=200,value=${{ env.ANTORA_VERSION }}
      - name: Login to DockerHub
        uses: docker/login-action@v1.8.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2.4.0
        with:
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
      - name: Update Docker Hub repo description from README.md
        uses: peter-evans/dockerhub-description@v2.4.2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: ${{ env.IMAGE_REPO }}
          readme-filepath: ./docs/docker/README.md
